1. Change cutoff for percentage of NAs in CNV-level from 0.4 to 0.8, which means I include more CNVs.

In [2]:
import pandas as pd
import numpy as np
import os
cwd = os.path.expanduser("~/cnv-project/adsp_real_data")
ref_gene = pd.read_table(f"{cwd}/refGene.clean.gz", compression = "gzip", sep = "\t", header = 0)

In [18]:
del_comm_cnv = pd.read_csv(f"{cwd}/data/del_comm_adsp_hq.gz", compression="gzip", sep="\t")
del_comm_cnv = del_comm_cnv.drop(columns=["COUNTED","ALT"])
del_comm_cnv.iloc[:,0] = del_comm_cnv.iloc[:,0].str.replace('chr','')

n_cnv,n_cols = del_comm_cnv.shape

percent_na_indv = [del_comm_cnv.iloc[:,i].isna().sum() / n_cnv for i in range(4,n_cols)]
cutoff_indv = 0.2
indv_to_keep = [index for index, element in enumerate(percent_na_indv) if element <= cutoff_indv]
del_comm_cnv = del_comm_cnv.iloc[:,indv_to_keep]

n_indvs = del_comm_cnv.shape[1] - 4
percent_na_cnv = [del_comm_cnv.iloc[i,:].isna().sum() / (n_indvs) for i in range(n_cnv)] 
cutoff_cnv = 0.8
cnv_to_keep = [index for index, element in enumerate(percent_na_cnv) if element <= cutoff_cnv]
del_comm_cnv = del_comm_cnv.iloc[cnv_to_keep,:]

In [19]:
del_comm_cnv

,CHR,SNP,CM,POS,0:A-ACT-AC000014-BL-NCR-15AD78694,0:A-ACT-AC000034-BL-NCR-16AD84906,0:A-ACT-AC000057-BL-NCR-15AD78356,0:A-ACT-AC000072-BL-NCR-15AD77250,0:A-ACT-AC000088-BL-NCR-15AD76548,0:A-ACT-AC000092-BL-NCR-15AD78589,...,0:G-MSBB-MB000322-BR-MSBB-71983,0:G-MSBB-MB000323-BR-MSBB-71984,0:G-MSBB-MB000326-BR-MSBB-71987,0:G-MSBB-MB000327-BR-MSBB-71988,0:G-MSBB-MB000331-BR-MSBB-71993,0:G-MSBB-MB000332-BR-MSBB-71994,0:G-MSBB-MB000333-BR-MSBB-71995,0:G-MSBB-MB000334-BR-MSBB-71996,0:G-MSBB-MB000335-BR-MSBB-74458,0:G-MSBB-MB000337-BR-MSBB-76349
0,22,chr22:10710932-10711692:DEL:COVERAGE:comm,10710932,10711692,1.0,0.0,1.0,1.0,1.0,0.0,...,1.0,1.0,1.0,0.0,NaN,1.0,1.0,1.0,1.0,0.0
1,22,chr22:10720746-10721165:DEL:COVERAGE:comm,10720746,10721165,1.0,1.0,1.0,NaN,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,NaN,1.0
2,22,chr22:10740324-10746330:DEL:AGGREGATED:comm,10740324,10746330,0.0,0.0,0.0,NaN,0.0,NaN,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0
3,22,chr22:11027506-11027616:DEL:AGGREGATED:comm,11027506,11027616,1.0,0.0,1.0,1.0,NaN,0.0,...,NaN,0.0,1.0,0.0,NaN,0.0,0.0,0.0,NaN,NaN
4,22,chr22:11030980-11031063:DEL:BREAKPOINT:comm,11030980,11031063,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9361,12,chr12:132730334-132730397:DEL:AGGREGATED:comm,132730334,132730397,2.0,2.0,1.0,1.0,1.0,2.0,...,1.0,2.0,0.0,2.0,NaN,1.0,1.0,1.0,2.0,NaN
9362,12,chr12:132776123-132776202:DEL:AGGREGATED:comm,132776123,132776202,2.0,2.0,2.0,2.0,NaN,2.0,...,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
9363,12,chr12:132844445-132844791:DEL:AGGREGATED:comm,132844445,132844791,0.0,0.0,0.0,NaN,NaN,0.0,...,NaN,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN
9364,12,chr12:132868863-132869205:DEL:COVERAGE:comm,132868863,132869205,1.0,1.0,NaN,NaN,1.0,1.0,...,NaN,1.0,1.0,1.0,1.0,NaN,1.0,2.0,2.0,1.0
9365,12,chr12:133091389-133096324:DEL:COVERAGE:comm,133091389,133096324,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
cnv_in_chr22 = del_comm_cnv[del_comm_cnv['CHR'] == '22'].iloc[:,range(4)]
genes_in_chr22 = ref_gene[ref_gene['CHR'] == '22']

In [25]:
cnv_in_chr22

    CHR                                          SNP        CM       POS
0    22    chr22:10710932-10711692:DEL:COVERAGE:comm  10710932  10711692
1    22    chr22:10720746-10721165:DEL:COVERAGE:comm  10720746  10721165
2    22  chr22:10740324-10746330:DEL:AGGREGATED:comm  10740324  10746330
3    22  chr22:11027506-11027616:DEL:AGGREGATED:comm  11027506  11027616
4    22  chr22:11030980-11031063:DEL:BREAKPOINT:comm  11030980  11031063
..   ..                                          ...       ...       ...
194  22  chr22:50189690-50189748:DEL:AGGREGATED:comm  50189690  50189748
195  22  chr22:50225576-50225636:DEL:AGGREGATED:comm  50225576  50225636
196  22  chr22:50381256-50381410:DEL:AGGREGATED:comm  50381256  50381410
197  22  chr22:50405325-50405406:DEL:AGGREGATED:comm  50405325  50405406
198  22    chr22:50716009-50716091:DEL:COVERAGE:comm  50716009  50716091

[199 rows x 4 columns]

In [26]:
genes_in_chr22

      CHR     start       end                 gene
26593  22  16150528  16193009               DUXAP8
26594  22  16157078  16172265            BMS1P22@3
26595  22  16162065  16172265  BMS1P17@3,BMS1P18@3
26596  22  16199675  16237070                PSLNR
26597  22  16256331  16287937                POTEH
...    ..       ...       ...                  ...
27241  22  51112818  51171640               SHANK3
27242  22  51174256  51176597         LOC105373100
27243  22  51176631  51183767                  ACR
27244  22  51195513  51238065            RPL23AP82
27245  22  51205934  51222064               RABL2B

[653 rows x 4 columns]

In [27]:
chr22_df = cnv_in_chr22.merge(genes_in_chr22, how='left', on='CHR')
chr22_df

,CHR,SNP,CM,POS,start,end,gene
0,22,chr22:10710932-10711692:DEL:COVERAGE:comm,10710932,10711692,16150528,16193009,DUXAP8
1,22,chr22:10710932-10711692:DEL:COVERAGE:comm,10710932,10711692,16157078,16172265,BMS1P22@3
2,22,chr22:10710932-10711692:DEL:COVERAGE:comm,10710932,10711692,16162065,16172265,"BMS1P17@3,BMS1P18@3"
3,22,chr22:10710932-10711692:DEL:COVERAGE:comm,10710932,10711692,16199675,16237070,PSLNR
4,22,chr22:10710932-10711692:DEL:COVERAGE:comm,10710932,10711692,16256331,16287937,POTEH
...,...,...,...,...,...,...,...
129942,22,chr22:50716009-50716091:DEL:COVERAGE:comm,50716009,50716091,51112818,51171640,SHANK3
129943,22,chr22:50716009-50716091:DEL:COVERAGE:comm,50716009,50716091,51174256,51176597,LOC105373100
129944,22,chr22:50716009-50716091:DEL:COVERAGE:comm,50716009,50716091,51176631,51183767,ACR
129945,22,chr22:50716009-50716091:DEL:COVERAGE:comm,50716009,50716091,51195513,51238065,RPL23AP82
129946,22,chr22:50716009-50716091:DEL:COVERAGE:comm,50716009,50716091,51205934,51222064,RABL2B

In [31]:
mask = (
        (chr22_df['CM'] >= chr22_df['start']) & (chr22_df['CM'] <= chr22_df['end']) |
        (chr22_df['CM'] <= chr22_df['start']) & (chr22_df['POS'] >= chr22_df['end']) |
        (chr22_df['POS'] >= chr22_df['start']) & (chr22_df['POS'] <= chr22_df['end'])
       )
overlap_df = chr22_df[mask]
overlap_df

,CHR,SNP,CM,POS,start,end,gene
17024,22,chr22:18990063-18990127:DEL:BREAKPOINT:comm,18990063,18990127,18958010,19018755,DGCR5
17680,22,chr22:19076248-19076387:DEL:AGGREGATED:comm,19076248,19076387,19023794,19109967,DGCR2
18993,22,chr22:19168421-19168478:DEL:AGGREGATED:comm,19168421,19168478,19166985,19279242,CLTCL1
19646,22,chr22:19260392-19260579:DEL:AGGREGATED:comm,19260392,19260579,19166985,19279242,CLTCL1
22272,22,chr22:19924994-19925883:DEL:AGGREGATED:comm,19924994,19925883,19863040,19929341,TXNRD2
...,...,...,...,...,...,...,...
124679,22,chr22:49973805-49975365:DEL:COVERAGE:comm,49973805,49975365,49808173,50051167,C22orf34
125332,22,chr22:50026295-50026405:DEL:AGGREGATED:comm,50026295,50026405,49808173,50051167,C22orf34
125985,22,chr22:50028934-50029409:DEL:COVERAGE:comm,50028934,50029409,49808173,50051167,C22orf34
127293,22,chr22:50189690-50189748:DEL:AGGREGATED:comm,50189690,50189748,50166925,50221521,BRD1
129922,22,chr22:50716009-50716091:DEL:COVERAGE:comm,50716009,50716091,50713407,50746075,PLXNB2

In [33]:
overlap_df_indv = overlap_df.merge(del_comm_cnv[['SNP','0:A-ACT-AC000014-BL-NCR-15AD78694']], how='inner', on='SNP')
overlap_df_indv

,CHR,SNP,CM,POS,start,end,gene,0:A-ACT-AC000014-BL-NCR-15AD78694
0,22,chr22:18990063-18990127:DEL:BREAKPOINT:comm,18990063,18990127,18958010,19018755,DGCR5,NaN
1,22,chr22:19076248-19076387:DEL:AGGREGATED:comm,19076248,19076387,19023794,19109967,DGCR2,0.0
2,22,chr22:19168421-19168478:DEL:AGGREGATED:comm,19168421,19168478,19166985,19279242,CLTCL1,1.0
3,22,chr22:19260392-19260579:DEL:AGGREGATED:comm,19260392,19260579,19166985,19279242,CLTCL1,NaN
4,22,chr22:19924994-19925883:DEL:AGGREGATED:comm,19924994,19925883,19863040,19929341,TXNRD2,0.0
...,...,...,...,...,...,...,...,...
100,22,chr22:49973805-49975365:DEL:COVERAGE:comm,49973805,49975365,49808173,50051167,C22orf34,2.0
101,22,chr22:50026295-50026405:DEL:AGGREGATED:comm,50026295,50026405,49808173,50051167,C22orf34,1.0
102,22,chr22:50028934-50029409:DEL:COVERAGE:comm,50028934,50029409,49808173,50051167,C22orf34,0.0
103,22,chr22:50189690-50189748:DEL:AGGREGATED:comm,50189690,50189748,50166925,50221521,BRD1,NaN
104,22,chr22:50716009-50716091:DEL:COVERAGE:comm,50716009,50716091,50713407,50746075,PLXNB2,2.0

In [36]:
gene_dict = {}
for g in overlap_df_indv['gene'].unique():
    gene_dict[g] = []
    if (overlap_df_indv[overlap_df_indv['gene'] == g]['0:A-ACT-AC000014-BL-NCR-15AD78694']).sum() != 0:
        gene_dict[g].append(1)
    else:
        gene_dict[g].append(0)
        
res = pd.DataFrame(gene_dict)
res

,DGCR5,DGCR2,CLTCL1,TXNRD2,ARVCF,ZDHHC8,FAM230G,YPEL1,IGLL5,RAB36,...,TTC38,TRMU,CELSR1,GRAMD4,TBC1D22A,LOC284930,TAFA5,C22orf34,BRD1,PLXNB2
0,0,0,1,0,1,0,0,0,0,1,...,0,0,0,0,1,1,1,1,0,1